services:
  - type: web
    name: invoice-backend
    runtime: python
    plan: free                    # ADD THIS LINE
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: invoice-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: AZURE_ENDPOINT
        sync: false
      - key: AZURE_KEY
        sync: false

databases:
  - name: invoice-db
    plan: free                    # ADD THIS LINE
    databaseName: invoice_db
    user: invoice_user